export const data = [
  {
    id: 0,
    query: "SELECT * FROM territories WHERE regionID > 0;",
    headcells: [
      {
        id: "territoryID",
        numeric: false,
        disablePadding: true,
        label: "territoryID",
      },
      {
        id: "territoryDescription",
        numeric: false,
        disablePadding: true,
        label: "territoryDescription",
      },
      {
        id: "regionID",
        numeric: false,
        disablePadding: true,
        label: "regionID",
      },
    ],
    output: [
      {
        territoryID: "01581",
        territoryDescription: "Westboro",
        regionID: 1,
      },
      {
        territoryID: "01730",
        territoryDescription: "Bedford",
        regionID: 1,
      },
      {
        territoryID: "01833",
        territoryDescription: "Georgetow",
        regionID: 1,
      },
      {
        territoryID: "02116",
        territoryDescription: "Boston",
        regionID: 1,
      },
      {
        territoryID: "02139",
        territoryDescription: "Cambridge",
        regionID: 1,
      },
      {
        territoryID: "02184",
        territoryDescription: "Braintree",
        regionID: 1,
      },
      {
        territoryID: "02903",
        territoryDescription: "Providence",
        regionID: 1,
      },
      {
        territoryID: "03049",
        territoryDescription: "Hollis",
        regionID: 3,
      },
      {
        territoryID: "03801",
        territoryDescription: "Portsmouth",
        regionID: 3,
      },
      {
        territoryID: "06897",
        territoryDescription: "Wilton",
        regionID: 1,
      },
      {
        territoryID: "07960",
        territoryDescription: "Morristown",
        regionID: 1,
      },
      {
        territoryID: "08837",
        territoryDescription: "Edison",
        regionID: 1,
      },
      {
        territoryID: 10019,
        territoryDescription: "NewYork",
        regionID: 1,
      },
      {
        territoryID: 10038,
        territoryDescription: "NewYork",
        regionID: 1,
      },
      {
        territoryID: 11747,
        territoryDescription: "Mellvile",
        regionID: 1,
      },
      {
        territoryID: 14450,
        territoryDescription: "Fairport",
        regionID: 1,
      },
      {
        territoryID: 19428,
        territoryDescription: "Philadelphia",
        regionID: 3,
      },
      {
        territoryID: 19713,
        territoryDescription: "Neward",
        regionID: 1,
      },
      {
        territoryID: 20852,
        territoryDescription: "Rockville",
        regionID: 1,
      },
      {
        territoryID: 27403,
        territoryDescription: "Greensboro",
        regionID: 1,
      },
      {
        territoryID: 27511,
        territoryDescription: "Cary",
        regionID: 1,
      },
      {
        territoryID: 29202,
        territoryDescription: "Columbia",
        regionID: 4,
      },
      {
        territoryID: 30346,
        territoryDescription: "Atlanta",
        regionID: 4,
      },
      {
        territoryID: 31406,
        territoryDescription: "Savannah",
        regionID: 4,
      },
      {
        territoryID: 32859,
        territoryDescription: "Orlando",
        regionID: 4,
      },
      {
        territoryID: 33607,
        territoryDescription: "Tampa",
        regionID: 4,
      },
      {
        territoryID: 40222,
        territoryDescription: "Louisville",
        regionID: 1,
      },
      {
        territoryID: 44122,
        territoryDescription: "Beachwood",
        regionID: 3,
      },
      {
        territoryID: 45839,
        territoryDescription: "Findlay",
        regionID: 3,
      },
      {
        territoryID: 48075,
        territoryDescription: "Southfield",
        regionID: 3,
      },
      {
        territoryID: 48084,
        territoryDescription: "Troy",
        regionID: 3,
      },
      {
        territoryID: 48304,
        territoryDescription: "BloomfieldHills",
        regionID: 3,
      },
      {
        territoryID: 53404,
        territoryDescription: "Racine",
        regionID: 3,
      },
      {
        territoryID: 55113,
        territoryDescription: "Roseville",
        regionID: 3,
      },
      {
        territoryID: 55439,
        territoryDescription: "Minneapolis",
        regionID: 3,
      },
      {
        territoryID: 60179,
        territoryDescription: "HoffmanEstates",
        regionID: 2,
      },
      {
        territoryID: 60601,
        territoryDescription: "Chicago",
        regionID: 2,
      },
      {
        territoryID: 72716,
        territoryDescription: "Bentonville",
        regionID: 4,
      },
      {
        territoryID: 75234,
        territoryDescription: "Dallas",
        regionID: 4,
      },
      {
        territoryID: 78759,
        territoryDescription: "Austin",
        regionID: 4,
      },
      {
        territoryID: 80202,
        territoryDescription: "Denver",
        regionID: 2,
      },
      {
        territoryID: 80909,
        territoryDescription: "ColoradoSprings",
        regionID: 2,
      },
      {
        territoryID: 85014,
        territoryDescription: "Phoenix",
        regionID: 2,
      },
      {
        territoryID: 85251,
        territoryDescription: "Scottsdale",
        regionID: 2,
      },
      {
        territoryID: 90405,
        territoryDescription: "SantaMonica",
        regionID: 2,
      },
      {
        territoryID: 94025,
        territoryDescription: "MenloPark",
        regionID: 2,
      },
      {
        territoryID: 94105,
        territoryDescription: "SanFrancisco",
        regionID: 2,
      },
      {
        territoryID: 95008,
        territoryDescription: "Campbell",
        regionID: 2,
      },
      {
        territoryID: 95054,
        territoryDescription: "SantaClara",
        regionID: 2,
      },
      {
        territoryID: 95060,
        territoryDescription: "SantaCruz",
        regionID: 2,
      },
      {
        territoryID: 98004,
        territoryDescription: "Bellevue",
        regionID: 2,
      },
      {
        territoryID: 98052,
        territoryDescription: "Redmond",
        regionID: 2,
      },
      {
        territoryID: 98104,
        territoryDescription: "Seattle",
        regionID: 2,
      },
    ],
  },
  {
    id: 1,
    query: "SELECT * FROM suppliers;",
    headcells: [
      {
        id: "supplierID",
        numeric: false,
        disablePadding: true,
        label: "supplierID",
      },
      {
        id: "companyName",
        numeric: false,
        disablePadding: true,
        label: "companyName",
      },
      {
        id: "contactName",
        numeric: false,
        disablePadding: true,
        label: "contactName",
      },
      {
        id: "contactTitle",
        numeric: false,
        disablePadding: true,
        label: "contactTitle",
      },
      {
        id: "address",
        numeric: false,
        disablePadding: true,
        label: "address",
      },
      {
        id: "city",
        numeric: false,
        disablePadding: true,
        label: "city",
      },
      {
        id: "region",
        numeric: false,
        disablePadding: true,
        label: "region",
      },
      {
        id: "postalCode",
        numeric: false,
        disablePadding: true,
        label: "postalCode",
      },
      {
        id: "country",
        numeric: false,
        disablePadding: true,
        label: "country",
      },
      {
        id: "phone",
        numeric: false,
        disablePadding: true,
        label: "phone",
      },
      {
        id: "fax",
        numeric: false,
        disablePadding: true,
        label: "fax",
      },
      {
        id: "homePage",
        numeric: false,
        disablePadding: true,
        label: "homePage",
      },
    ],
    output: [
      {
        supplierID: 1,
        companyName: "Exotic Liquids",
        contactName: "Charlotte Cooper",
        contactTitle: "Purchasing Manager",
        address: "49 Gilbert St.",
        city: "London",
        region: "NULL",
        postalCode: "EC1 4SD",
        country: "UK",
        phone: "(171) 555-2222",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 2,
        companyName: "New Orleans Cajun Delights",
        contactName: "Shelley Burke",
        contactTitle: "Order Administrator",
        address: "P.O. Box 78934",
        city: "New Orleans",
        region: "LA",
        postalCode: 70117,
        country: "USA",
        phone: "(100) 555-4822",
        fax: "NULL",
        homePage: "#CAJUN.HTM#",
      },
      {
        supplierID: 3,
        companyName: "Grandma Kelly's Homestead",
        contactName: "Regina Murphy",
        contactTitle: "Sales Representative",
        address: "707 Oxford Rd.",
        city: "Ann Arbor",
        region: "MI",
        postalCode: 48104,
        country: "USA",
        phone: "(313) 555-5735",
        fax: "(313) 555-3349",
        homePage: "NULL",
      },
      {
        supplierID: 4,
        companyName: "Tokyo Traders",
        contactName: "Yoshi Nagase",
        contactTitle: "Marketing Manager",
        address: "9-8 Sekimai Musashino-shi",
        city: "Tokyo",
        region: "NULL",
        postalCode: 100,
        country: "Japan",
        phone: "(03) 3555-5011",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 5,
        companyName: "Cooperativa de Quesos 'Las Cabras'",
        contactName: "Antonio del Valle Saavedra",
        contactTitle: "Export Administrator",
        address: "Calle del Rosal 4",
        city: "Oviedo",
        region: "Asturias",
        postalCode: 33007,
        country: "Spain",
        phone: "(98) 598 76 54",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 6,
        companyName: "Mayumi's",
        contactName: "Mayumi Ohno",
        contactTitle: "Marketing Representative",
        address: "92 Setsuko Chuo-ku",
        city: "Osaka",
        region: "NULL",
        postalCode: 545,
        country: "Japan",
        phone: "(06) 431-7877",
        fax: "NULL",
        homePage:
          "Mayumi's (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/mayumi.htm#",
      },
      {
        supplierID: 7,
        companyName: "Pavlova Ltd.",
        contactName: "Ian Devling",
        contactTitle: "Marketing Manager",
        address: "74 Rose St. Moonie Ponds",
        city: "Melbourne",
        region: "Victoria",
        postalCode: 3058,
        country: "Australia",
        phone: "(03) 444-2343",
        fax: "(03) 444-6588",
        homePage: "NULL",
      },
      {
        supplierID: 8,
        companyName: "Specialty Biscuits Ltd.",
        contactName: "Peter Wilson",
        contactTitle: "Sales Representative",
        address: "29 King's Way",
        city: "Manchester",
        region: "NULL",
        postalCode: "M14 GSD",
        country: "UK",
        phone: "(161) 555-4448",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 9,
        companyName: "PB Knäckebröd AB",
        contactName: "Lars Peterson",
        contactTitle: "Sales Agent",
        address: "Kaloadagatan 13",
        city: "Göteborg",
        region: "NULL",
        postalCode: "S-345 67",
        country: "Sweden",
        phone: "031-987 65 43",
        fax: "031-987 65 91",
        homePage: "NULL",
      },
      {
        supplierID: 10,
        companyName: "Refrescos Americanas LTDA",
        contactName: "Carlos Diaz",
        contactTitle: "Marketing Manager",
        address: "Av. das Americanas 12.890",
        city: "Sao Paulo",
        region: "NULL",
        postalCode: 5442,
        country: "Brazil",
        phone: "(11) 555 4640",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 11,
        companyName: "Heli Süßwaren GmbH & Co. KG",
        contactName: "Petra Winkler",
        contactTitle: "Sales Manager",
        address: "Tiergartenstraße 5",
        city: "Berlin",
        region: "NULL",
        postalCode: 10785,
        country: "Germany",
        phone: "(010) 9984510",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 12,
        companyName: "Plutzer Lebensmittelgroßmärkte AG",
        contactName: "Martin Bein",
        contactTitle: "International Marketing Mgr.",
        address: "Bogenallee 51",
        city: "Frankfurt",
        region: "NULL",
        postalCode: 60439,
        country: "Germany",
        phone: "(069) 992755",
        fax: "NULL",
        homePage:
          "Plutzer (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/plutzer.htm#",
      },
      {
        supplierID: 13,
        companyName: "Nord-Ost-Fisch Handelsgesellschaft mbH",
        contactName: "Sven Petersen",
        contactTitle: "Coordinator Foreign Markets",
        address: "Frahmredder 112a",
        city: "Cuxhaven",
        region: "NULL",
        postalCode: 27478,
        country: "Germany",
        phone: "(04721) 8713",
        fax: "(04721) 8714",
        homePage: "NULL",
      },
      {
        supplierID: 14,
        companyName: "Formaggi Fortini s.r.l.",
        contactName: "Elio Rossi",
        contactTitle: "Sales Representative",
        address: "Viale Dante 75",
        city: "Ravenna",
        region: "NULL",
        postalCode: 48100,
        country: "Italy",
        phone: "(0544) 60323",
        fax: "(0544) 60603",
        homePage: "#FORMAGGI.HTM#",
      },
      {
        supplierID: 15,
        companyName: "Norske Meierier",
        contactName: "Beate Vileid",
        contactTitle: "Marketing Manager",
        address: "Hatlevegen 5",
        city: "Sandvika",
        region: "NULL",
        postalCode: 1320,
        country: "Norway",
        phone: "(0)2-953010",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 16,
        companyName: "Bigfoot Breweries",
        contactName: "Cheryl Saylor",
        contactTitle: "Regional Account Rep.",
        address: "3400 - 8th Avenue Suite 210",
        city: "Bend",
        region: "OR",
        postalCode: 97101,
        country: "USA",
        phone: "(503) 555-9931",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 17,
        companyName: "Svensk Sjöföda AB",
        contactName: "Michael Björn",
        contactTitle: "Sales Representative",
        address: "Brovallavägen 231",
        city: "Stockholm",
        region: "NULL",
        postalCode: "S-123 45",
        country: "Sweden",
        phone: "08-123 45 67",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 18,
        companyName: "Aux joyeux ecclésiastiques",
        contactName: "Guylène Nodier",
        contactTitle: "Sales Manager",
        address: "203 Rue des Francs-Bourgeois",
        city: "Paris",
        region: "NULL",
        postalCode: 75004,
        country: "France",
        phone: "(1) 03.83.00.68",
        fax: "(1) 03.83.00.62",
        homePage: "NULL",
      },
      {
        supplierID: 19,
        companyName: "New England Seafood Cannery",
        contactName: "Robb Merchant",
        contactTitle: "Wholesale Account Agent",
        address: "Order Processing Dept. 2100 Paul Revere Blvd.",
        city: "Boston",
        region: "MA",
        postalCode: "02134",
        country: "USA",
        phone: "(617) 555-3267",
        fax: "(617) 555-3389",
        homePage: "NULL",
      },
      {
        supplierID: 20,
        companyName: "Leka Trading",
        contactName: "Chandra Leka",
        contactTitle: "Owner",
        address: "471 Serangoon Loop Suite #402",
        city: "Singapore",
        region: "NULL",
        postalCode: "0512",
        country: "Singapore",
        phone: "555-8787",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 21,
        companyName: "Lyngbysild",
        contactName: "Niels Petersen",
        contactTitle: "Sales Manager",
        address: "Lyngbysild Fiskebakken 10",
        city: "Lyngby",
        region: "NULL",
        postalCode: 2800,
        country: "Denmark",
        phone: 43844108,
        fax: 43844115,
        homePage: "NULL",
      },
      {
        supplierID: 22,
        companyName: "Zaanse Snoepfabriek",
        contactName: "Dirk Luchte",
        contactTitle: "Accounting Manager",
        address: "Verkoop Rijnweg 22",
        city: "Zaandam",
        region: "NULL",
        postalCode: "9999 ZZ",
        country: "Netherlands",
        phone: "(12345) 1212",
        fax: "(12345) 1210",
        homePage: "NULL",
      },
      {
        supplierID: 23,
        companyName: "Karkki Oy",
        contactName: "Anne Heikkonen",
        contactTitle: "Product Manager",
        address: "Valtakatu 12",
        city: "Lappeenranta",
        region: "NULL",
        postalCode: 53120,
        country: "Finland",
        phone: "(953) 10956",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 24,
        companyName: "G'day Mate",
        contactName: "Wendy Mackenzie",
        contactTitle: "Sales Representative",
        address: "170 Prince Edward Parade Hunter's Hill",
        city: "Sydney",
        region: "NSW",
        postalCode: 2042,
        country: "Australia",
        phone: "(02) 555-5914",
        fax: "(02) 555-4873",
        homePage:
          "G'day Mate (on the World Wide Web)#http://www.microsoft.com/accessdev/sampleapps/gdaymate.htm#",
      },
      {
        supplierID: 25,
        companyName: "Ma Maison",
        contactName: "Jean-Guy Lauzon",
        contactTitle: "Marketing Manager",
        address: "2960 Rue St. Laurent",
        city: "Montréal",
        region: "Québec",
        postalCode: "H1J 1C3",
        country: "Canada",
        phone: "(514) 555-9022",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 26,
        companyName: "Pasta Buttini s.r.l.",
        contactName: "Giovanni Giudici",
        contactTitle: "Order Administrator",
        address: "Via dei Gelsomini 153",
        city: "Salerno",
        region: "NULL",
        postalCode: 84100,
        country: "Italy",
        phone: "(089) 6547665",
        fax: "(089) 6547667",
        homePage: "NULL",
      },
      {
        supplierID: 27,
        companyName: "Escargots Nouveaux",
        contactName: "Marie Delamare",
        contactTitle: "Sales Manager",
        address: "22 rue H. Voiron",
        city: "Montceau",
        region: "NULL",
        postalCode: 71300,
        country: "France",
        phone: "85.57.00.07",
        fax: "NULL",
        homePage: "NULL",
      },
      {
        supplierID: 28,
        companyName: "Gai pâturage",
        contactName: "Eliane Noz",
        contactTitle: "Sales Representative",
        address: "Bat. B 3 rue des Alpes",
        city: "Annecy",
        region: "NULL",
        postalCode: 74000,
        country: "France",
        phone: "38.76.98.06",
        fax: "38.76.98.58",
        homePage: "NULL",
      },
      {
        supplierID: 29,
        companyName: "Forêts d'érables",
        contactName: "Chantal Goulet",
        contactTitle: "Accounting Manager",
        address: "148 rue Chasseur",
        city: "Ste-Hyacinthe",
        region: "Québec",
        postalCode: "J2S 7S8",
        country: "Canada",
        phone: "(514) 555-2955",
        fax: "(514) 555-2921",
        homePage: "NULL",
      },
    ],
  },
  {
    id: 2,
    query: "SELECT * FROM shippers WHERE shipperID <= 3;",
    headcells: [
      {
        id: "shipperID",
        numeric: false,
        disablePadding: true,
        label: "shipperID",
      },
      {
        id: "companyName",
        numeric: false,
        disablePadding: true,
        label: "companyName",
      },
      {
        id: "phone",
        numeric: false,
        disablePadding: true,
        label: "phone",
      },
    ],
    output: [
      {
        shipperID: 1,
        companyName: "Speedy Express",
        phone: "(503) 555-9831",
      },
      {
        shipperID: 2,
        companyName: "United Package",
        phone: "(503) 555-3199",
      },
      {
        shipperID: 3,
        companyName: "Federal Shipping",
        phone: "(503) 555-9931",
      },
    ],
  },
];
export const suggestions = ["SELECT * FROM territories WHERE regionID > 0;", "SELECT * FROM suppliers;", "SELECT * FROM shippers WHERE shipperID <= 3;"];
